### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by anthonyyuan** [mahyarnajibi/fast-rcnn-torch#1] opened 2016-03-03 09:22 UTC
/Users/lihong/torch/install/bin/luajit: ./models/AlexNet/FRCNN.lua:60: attempt to index local 'opt' (a nil value)
stack traceback:
    # **# ./models/AlexNet/FRCNN.lua:60: in function <./models/AlexNet/FRCNN.lua:9>
    ./network/Net.lua:10: in function '__init'**
    /Users/lihong/torch/install/share/lua/5.1/torch/init.lua:91: in function </Users/lihong/torch/install/share/lua/5.1/torch/init.lua:87>
    [C]: in function 'Net'
    demo.lua:14: in main chunk
    [C]: in function 'dofile'
    ...hong/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
    [C]: at 0x010cc11bd0

**Comment by mahyarnajibi** [comment] 2016-04-08 12:26
The issue is addressed in commit aaa0a33.

**Comment by Ethiral** [comment] 2016-04-21 10:07
executing th man_trian.lua gives:-
/home/ekanshv/torch/install/bin/luajit: ...e/ekanshv/torch/install/share/lua/5.1/argcheck/usage.lua:82: attempt to index local 'rules' (a nil value)
stack traceback:
    ...e/ekanshv/torch/install/share/lua/5.1/argcheck/usage.lua:82: in function 'usage'
    datasets/argcheck.lua:61: in function 'initcheck'
    ./datasets/DataSetPascal.lua:113: in function '__init'
    /home/ekanshv/torch/install/share/lua/5.1/torch/init.lua:91: in function </home/ekanshv/torch/install/share/lua/5.1/torch/init.lua:87>
    [C]: in function 'DataSetPascal'
    main_train.lua:14: in main chunk
    [C]: in function 'dofile'
    ...nshv/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
    [C]: at 0x00406670

**Comment by mahyarnajibi** [comment] 2016-04-21 16:54
Did you download the proposals and the VOC 2007 dataset? This usually means that the dataset class can not find the proposals or the dataset root directory. If you want to use the default paths you should download the VOC 2007 dataset and move it to ./data/datasets/voc_2007/. For selective search proposals running ./scripts/get_proposals.sh should download and place the data in the default directory. Otherwise, you should change the paths using the command line (or directly in the config.lua) to point to the correct dataset and proposals paths.

**Comment by Ethiral** [comment] 2016-04-22 06:33
Want to train it for VOC2005 dataset(4 classes) but the annotations file is in .txt format.Any suggestions?

**Comment by mahyarnajibi** [comment] 2016-04-23 18:22
In this case, you need to write a class that inherits the DataSetDetection class and defines the virtual functions in this base class (As an example you can see the DataSetPascal class that handles VOC2007 and VOC2012 datasets). You also need to extract proposal boxes. You can do it by using the selective search code which is publicly available.

**Closed as completed** 2016-05-27 21:43 UTC
